name: Build and Publish Images on Docker Hub

on:
  push:
    paths-ignore:
      - 'LICENSE',
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE',
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push WP_CLI in PHP 7.4
        uses: docker/build-push-action@v2
        with:
          context: cli/php7.4/alpine
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wpcli-keep-running:cli-2.6-php7.4

      - name: Build and push WP_CLI in PHP 8.0
        uses: docker/build-push-action@v2
        with:
          context: cli/php8.0/alpine
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wpcli-keep-running:cli-2.6-php8.0

      - name: Build and push WP_CLI in PHP 8.1
        uses: docker/build-push-action@v2
        with:
          context: cli/php8.1/alpine
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wpcli-keep-running:cli-2.6-php8.1